spring:
  application:
    name: auth-service
  profiles:
    active: local
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/commkart
    username: commkart-user
    password: postgres
  jpa:
    hibernate.ddl-auto: create
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
    healthcheck:
      enabled: true
