spring:
  application:
    name: cmk-frontend
  profiles:
    active: local
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'