hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 2000
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  profiles:
    active: local
  cloud:
    loadBalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: auth-service
          uri: 'lb://auth-service'
          predicates:
            - Path=/auth/**
          filters:
            - name: Hystrix
              args:
                name: hystrix
                fallbackUri: 'forward:/fallback/auth'
        - id: core-service
          uri: 'lb://core-service'
          predicates:
            - Path=/core/**
          filters:
            - name: Hystrix
              args:
                name: hystrix
                fallbackUri: 'forward:/fallback/core'
        - id: hystrix-dashboard
          uri: 'lb://hystrix-dashboard'
          predicates:
            - Path=/hx-dash/**
          filters:
            - name: Hystrix
              args:
                name: hystrix
                fallbackUri: 'forward:/fallback/hystrix'
