hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 2000
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  profiles:
    active: local
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: 'lb://auth-service'
          predicates:
            - Path=/auth/**
          filters:
            - name: Hystrix
              args:
                name: hystrix
                fallbackUri: 'forward:/fallback/auth'
        - id: ck-main
          uri: 'lb://ck-main'
          predicates:
            - Path=/ck/**
          filters:
            - name: Hystrix
              args:
                name: hystrix
                fallbackUri: 'forward:/fallback/ck'
