spring:
  application:
    name: core-service
  profiles:
    active: local
  cloud:
    loadBalancer:
      ribbon:
        enabled: false
server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
    healthcheck:
      enabled: true
